### ISSUE TITLE
compiler requirements

### ISSUE THREAD

**Issue by lmfeeney** [ilabrg/artifacts-conext21-ble#3]
For completeness, it might be helpful to include a compiler version in the readme.  I used 9.2.1.  IIRC, nRF's own software had some version constraints?, but I could be mis-remembering.   In any case, it's probably a good idea, just for long-term re-usability and not getting bitten by some compiler issue later.

**Comment by haukepetersen** [comment]
Building RIOT and NimBLE is actually not very restrictive on the gcc version to be used. In our case, all experiments were carried out using `gcc 9.3.1`. I added this information to the README.md (23654816de87eab7f083fd358dabe985d9d88152).
